.TH "MARKIT" "1" "November 2015" "Version 0.1" "User Commands"
.SH NAME
markit \- Bookmark manager. Your private Google.
.SH SYNOPSIS
.B markit
.RI [ OPTIONS ]
.I KEYWORDS...
.SH DESCRIPTION
.B markit
is a command line tool to save and search bookmarks.
.PP
The SQLite3 database file is stored in $HOME/.cache/bookmarks.db for each user.
.PP
It's advisable to copy URLs directly from the browser address bar, i.e., along with the leading `http://` or `htts://` token. markit looks up title data (found within <title></title> tags of HTML) from the web only for fully-formed HTTP or HTTPS URLs.
.PP
You can either add or update or delete record(s) in one instance. A combination of these operations are not supported in a single instance.
.PP
Search works in mysterious ways. All the keywords are treated as a single tag together. Partial sequential tag matches are shown in results. The same keywords are separately searched as unique tokens so that entries with matching URL or title data are also shown in results.
.SH OPTIONS
.TP
.BI \-a " URL" " " "tag 1", " tag 2", " ..."
Bookmark
.I URL
along with comma separated tags. A tag can have multiple words.
.TP
.BI \-d " N"
Delete bookmark at index
.I N
(as shown in `-p` output).
.TP
.B \-D
Delete ALL bookmarks.
.TP
.BI \-i " N"
Add a new record at index
.I N
of the database. Works only if `-a` option is used. Use this option to fill blank indexes left by deleted bookmarks.
.TP
.BI \-o
Fetch title data from the web. Works only with `-a` or `-u` options.
.TP
.B \-p
Show all bookmark records from the database along with actual index. Shows URL, tags and title data.
.TP
.BI \-s " keywords"
Search bookmarks for a (partial) tag or keywords and show the results. Prompts to enter result number to open in browser. Note that the sequential index number may not match the real index in database. The results show URL and title data (tags are not shown).
.TP
.BI \-u " N"
Update bookmark at index
.I N
(as shown in `-p` output).
.TP
.BI \-z
Enable debugging.
.TP
.BI ""
Any other option shows help and exits markit.
.SH KEYS
.TP
.BI "1-N"
Open
.I Nth
search result in browser. Pressing `Enter` exits markit.
.SH ENVIRONMENT
.TP
.BI BROWSER
Overrides the default browser. Ref:
.I http://docs.python.org/library/webbrowser.html
.SH AUTHOR
Written by Arun Prakash Jana <engineerarun@gmail.com>.
.SH HOME
.I https://github.com/jarun/markit
.SH REPORTING BUGS
.I https://github.com/jarun/markit/issues
.SH COPYRIGHT
Copyright \(co 2015 Arun Prakash Jana <engineerarun@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
