.TH "MARKIT" "1" "November 2015" "Version 1.0" "User Commands"
.SH NAME
markit \- Bookmark manager. Your private Google.
.SH SYNOPSIS
.B markit
.RI [ OPTIONS ]
.I KEYWORDS...
.SH DESCRIPTION
.B markit
is a command line tool to save and search bookmarks.
.PP
The SQLite3 database file is stored in $HOME/.cache/bookmarks.db for each user.
.SH OPERATIONAL NOTES
It's advisable to copy URLs directly from the browser address bar, i.e., along with the leading 'http://' or 'https://' token. markit looks up title data (found within <title></title> tags of HTML) from the web ONLY for fully-formed HTTP(S) URLs.
.PP
If the URL contains characters like ';', '&' or brackets they may be interpreted specially by the shell. To avoid it, add the URL within single ''' or double '"' qoutes.
.PP
The same URL cannot be added twice. You can update tags and re-fetch title data. You can also delete it and insert at the same index.
.PP
You can either add or update or delete record(s) in one instance. A combination of these operations is not supported in a single run.
.PP
Search works in mysterious ways:
  - Substrings match ('match' matches 'rematched') for URL, tags and title data.
  - All the keywords are treated together as a 'single' tag in the same order. Bookmarks with partial or complete tag matches are shown in results.
  - The same keywords are treated 'separately' as unique tokens. Hence, entries with matching URL or title data are also shown in the results. Order is irrelevant in this case.
  - Search results are indexed serially. The index is different from actual database index of a bookmark record. Use '-P' option to get DB index.
.SH OPTIONS
.TP
.BI \-a " URL" " " "tag 1", " tag 2", " ..."
Bookmark
.I URL
along with comma separated tags. A tag can have multiple words. The same URL cannot be added twice.
.TP
.BI \-d " N"
Delete bookmark at index
.I N
in DB (from `-P` output).
.TP
.B \-D
Delete ALL bookmarks.
.TP
.BI \-i " N"
Add a new record at index
.I N
in DB. Use this option to fill blank indices left by deleted bookmarks.
.TP
.BI \-o " N"
Open URL at DB index
.I N
in browser.
.TP
.BI \-p " N"
Show details of bookmark record stored at index
.I N
in DB.
.TP
.B \-P
Show all bookmark records from the DB along with actual index. Shows URL, title data and tags.
.TP
.BI \-s " keywords"
Search bookmarks for a (partial) tag or keywords and show the results. Prompts to enter result number to open in browser. Note that the sequential index number may not match the real index in database. Shows URL, title data and tags.
.TP
.BI \-u " N"
Update bookmark at index
.I N
in DB.
.TP
.BI \-w
Fetch title data from the web. Works with `-a`, `-i` or `-u` options.
.TP
.BI \-z
Enable debugging.
.TP
.BI ""
Any other option shows help and exits markit.
.SH KEYS
.TP
.BI "1-N"
Open
.I Nth
search result in browser. Pressing `Enter` exits markit.
.SH ENVIRONMENT
.TP
.BI BROWSER
Overrides the default browser. Ref:
.I http://docs.python.org/library/webbrowser.html
.SH AUTHOR
Written by Arun Prakash Jana <engineerarun@gmail.com>.
.SH HOME
.I https://github.com/jarun/markit
.SH REPORTING BUGS
.I https://github.com/jarun/markit/issues
.SH COPYRIGHT
Copyright \(co 2015 Arun Prakash Jana <engineerarun@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
